#########################################
#                                       #
#               MY_VERIFY               #
#                                       #
#########################################

#Contact with me:
#
#VK: vk.com/deelter
#DISCORD: DeelTer#4782
#TWITTER: twitter.com/roma200315
#YOUTUBE: www.youtube.com/channel/UCRACU2JfOfClrlEHImv5pYw

settings:
  bot:
    guild: "GUILD_ID"
    token: "TOKEN"

  #Type your channels id's here
  channels: #Id's
    verify: "805152627271925810"
    logs: ""

  #Nickname that will be issued after verification
  nickname:
    enable: false
    updater-enable: true

  #Roles that will be issued after verification
  roles:
    enable: true
    id:
      - "ID1"
      - "ID2"

messages:
  discord:
    player-offline: "Такого `игрока` не существует,\nлибо вы неправильно ввели ник"
    account-exists: "Данный `игрок` уже зарегистрирован \nвведите другой ник"
    application-exists: "Заявка на `верификацию` уже была \nсоздана другим игроком"
    application-created: "Вы успешно создали заявку на верификацию \nПожалуйста, подтвердите её `в игре`"
    unlink: "Ваш аккаунт успешно `отвязан` от дискорда \nВы сможете привязать его повторно тем же способом"
  minecraft:
    no-perm: "%ni%Верификация:%ni2% Нет прав"
    reload: "%ni%Верификация:%ni2% Конфигурация успешно перезагружена"
    not-linked: "%ni%Верификация:%ni2% Ваш дискорд не привязан"
    success-unlink: "%ni%Верификация:%ni2% Вы успешно отвязали свой дискорд"
    no-applications: "%ni%Верификация:%ni2% Заявки на верификацию этого ника отсутствуют"
    success-link: "%ni%Верификация:%ni2% Вы успешно верифицировали свой аккаунт!"

#Use %COLOR%. Example: %br%◇ %cs% or %or%
custom-colors:
  ni: '#8B79FF'
  ni2: '#CAC4F5'

database:
  use-mysql: false
  mysql:
    name: ""
    host: ""
    port: 3306
    database: ""
    username: ""
    password: ""

debug: true